### PR TITLE
Switch to using Allow All auth provider

### PR DESCRIPTION
**Pull request by kenfinnigan**
Switched to using an auth provider that accepts any user/pwd combo. Figured that it would be ok for now, and maybe even appropriate for a local developer as well.

Couldn't figure out how to test it, but it didn't appear to break the vagrant provisioning

### CODE REVIEW

**Comment by pmuir** [comment]
I think the other option is to provide a password file. We could set up an admin user + a normal user with this, which might be a better option.

**Comment by kenfinnigan** [comment]
Sure, but I figured no security was better than defining some pre specified users/passwords that essentially result in no security because everyone knows what they're set to

**Comment by pmuir** [comment]
Maybe make a comment to this effect.

**Comment by pmuir** [comment]
I've broken this patch due to changing from multi-machine to single machine. Can you fix it up?

**Comment by kenfinnigan** [comment]
I'm going to close and fix it up properly into separate PRs

**Pull request closed without merging**
